version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=book_api
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=book_api
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql-data:
